/**
 * Email Report Sender (ESM)
 *
 * Sends revenue intelligence reports via Gmail SMTP.
 * Adapted from pricelabs-agent/email.js for ESM module format.
 *
 * Requires a Gmail App Password (not your regular password).
 * Create one at: https://myaccount.google.com/apppasswords
 */

import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function htmlEscape(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Send a revenue intelligence report via email.
 *
 * @param {string} reportPath — Path to the saved report file
 * @param {string} fullReport — Full report content (markdown)
 * @param {string[]} screenshots — Paths to screenshot attachments
 * @returns {Promise<Object>} — nodemailer send result
 */
export async function sendReport(reportPath, fullReport, screenshots = []) {
  const missing = ['GMAIL_USER', 'GMAIL_APP_PASSWORD', 'REPORT_TO_EMAIL']
    .filter(k => !process.env[k]);

  if (missing.length > 0) {
    throw new Error(`Missing required env vars for email: ${missing.join(', ')}`);
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const attachments = [];

  if (reportPath && fs.existsSync(reportPath)) {
    attachments.push({
      filename: path.basename(reportPath),
      path: reportPath,
    });
  }

  for (const screenshot of screenshots) {
    if (screenshot && fs.existsSync(screenshot)) {
      attachments.push({
        filename: path.basename(screenshot),
        path: screenshot,
      });
    }
  }

  const safeReport = htmlEscape(fullReport);

  const mailOptions = {
    from: process.env.GMAIL_USER,
    to: process.env.REPORT_TO_EMAIL,
    subject: `Solnest Stays — Revenue Intelligence Report — ${today}`,
    text: `Your revenue intelligence analysis is attached.\n\n${fullReport}`,
    html: `
      <h2>Solnest Stays — Revenue Intelligence Report</h2>
      <p><strong>${today}</strong></p>
      <hr>
      <pre style="font-family: monospace; white-space: pre-wrap; font-size: 14px;">${safeReport}</pre>
      <hr>
      <p><em>Generated by Revenue Intelligence Platform</em></p>
      <p><em>Powered by Python Revenue Engine + Claude Agent SDK</em></p>
    `,
    attachments,
  };

  const info = await transporter.sendMail(mailOptions);

  if (info.rejected && info.rejected.length > 0) {
    throw new Error(`Email rejected for recipients: ${info.rejected.join(', ')}`);
  }

  console.log(`[Email] Report sent: ${info.messageId}`);
  return info;
}
